/* autogenerated by Processing revision 1289 on 2023-02-13 */
import processing.core.*;
import processing.data.*;
import processing.event.*;
import processing.opengl.*;

import codeanticode.syphon.*;
import processing.video.*;

import java.util.HashMap;
import java.util.ArrayList;
import java.io.File;
import java.io.BufferedReader;
import java.io.PrintWriter;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.IOException;

public class syphoncam extends PApplet {



PGraphics canvas;
SyphonServer server;


Capture cam;

public void setup() { 
  /* size commented out by preprocessor */;
  canvas = createGraphics(640, 508, P3D);
  
  // Create syphon server to send frames out.
  server = new SyphonServer(this, "Processing Syphon");
  
  cam = new Capture(this, "pipeline:autovideosrc");
  cam.start();
}

public void draw() {
  if (cam.available() == true) {
    cam.read();
  }

  canvas.beginDraw();
  canvas.image(cam, 0, 0,640, 508);
  canvas.endDraw();
  
  image(canvas, 0, 0);
  server.sendImage(canvas);
}


  public void settings() { size(640, 508, P3D); }

  static public void main(String[] passedArgs) {
    String[] appletArgs = new String[] { "syphoncam" };
    if (passedArgs != null) {
      PApplet.main(concat(appletArgs, passedArgs));
    } else {
      PApplet.main(appletArgs);
    }
  }
}
